### ISSUE TITLE
PyNN exhausts NEST 2.6/2.8 synapse model storage

### ISSUE THREAD

**Issue by astoeckel** [NeuralEnsemble/PyNN#377]
Running code along the line of

    for i in xrange(257):
        sim.Projection(pop[0], pop[i], self.sim.FromListConnector([(0, 0, 0.03, 0.1)]))

causes the following NEST exception

    Oct 11 01:08:09 ConnectionManager::copy_synapse_prototype [Error]: 
    CopyModel cannot generate another synapse. Maximal synapse model count of 
    255 exceeded.

Backtrace:

      File "./run.py", line 55, in <module>
        output = sim.run(topo)
      File "/home/andreas/hbp-pynnless/pynnless/pynnless.py", line 786, in run
        self.sim.FromListConnector(descrs))
      File "/usr/lib/python2.7/site-packages/pyNN/nest/projections.py", line 48, in __init__
        self.nest_synapse_model = self.synapse_type._get_nest_synapse_model("projection_%d" % Projection._nProj)
      File "/usr/lib/python2.7/site-packages/pyNN/nest/synapses.py", line 45, in _get_nest_synapse_model
        nest.CopyModel(self.nest_name, label, synapse_defaults)
      File "/home/andreas/.local/lib64/python2.7/site-packages/nest/hl_api.py", line 154, in stack_checker_func
        return f(*args, **kwargs)
      File "/home/andreas/.local/lib64/python2.7/site-packages/nest/hl_api.py", line 591, in CopyModel
        sr("/%s /%s 3 2 roll CopyModel" % (existing, new))
      File "/home/andreas/.local/lib64/python2.7/site-packages/nest/__init__.py", line 81, in catching_sli_run
        raise hl_api.NESTError("{0} in {1}{2}".format(errorname, commandname, message))

It seems like PyNN unnecessarily causes the creation of a new synapse model, although the same synapse parameters are used for all created synapses, exhausting the limited synapse model storage in NEST.

This bug affects PyNN 0.8 and NEST 2.6.0 and 2.8.0. The bug does not occur with NEST 2.4.2.

**Comment by apdavison** [comment]
This is a limitation introduced in NEST 2.6.0, it appears.

I do not think there is a straightforward solution at the PyNN level, since synapse models are the only mechanism I'm aware of in NEST to uniquely label a set of connections (which is what a PyNN Projection is).

There are possible workarounds, such as having a `setup()`-level flag which disables modifying or introspecting Projections (e.g. the `Projection.get()` method would be disabled).

I'll discuss this with the NEST developers to see if there are alternative approaches I haven't thought of (@jougs is already aware of this ticket), or if there are plans to relax the limitation (255 synapse types seems like a rather small number for brain-scale simulations).

Meantime, it might be easier for you to write a new `Connector` class which makes all the connections within a single Projection.

**Comment by mschmidt87** [comment]
Hi,
the basic problem is that a synapse type in NEST is different from a projection in PyNN.
A synapse type in NEST specifies the dynamical model of synapse (e.g. static, STDP etc.) and not the projection/connection it belongs to. It also does not specify whether the synapse is excitatory or inhibitory, because this is independently decided by the synaptic weights.

Also, creating loads of different synapse types in NEST is generally not a good idea, if it's not necessary, because this creates a lot of memory overhead.

In NEST, there is noch such concept as a "Projection". So, there is no formal way to assign a single connection/synapse to a projection between populations of neurons. This is because this is a purely administrative problem which is irrelevant for the dynamics of the numerical simulation. Instead, filtering connections in NEST is done by a search where you can specify targets and sources.

Thus, my suggestion would be to think about a way to forward the identification of all synapses belonging to a projection to a search call in NEST (nest.GetConnections(...)). One could use the list of targets and sources of the pyNN projection as arguments for the search call. So, instead calling nest.GetConnections with a synapse type associated to the projection as it is done now, pyNN should rather specify sources and targets.

This would not be entirely unique because if you connect two populations with two "Projections" calls (i.e. two different pyNN projections), you won't be able to disinguish them afterwards anymore.
But this is probably not a sensible use case and  might be tolerable.

**Comment by apdavison** [comment]
Thanks for the input!

> This would not be entirely unique because if you connect two populations with two "Projections" calls (i.e. two different pyNN projections), you won't be able to disinguish them afterwards anymore.

Unfortunately this is exactly the problem. Even though it is not intended to be used this way, using the NEST synapse type as a label provides the only mechanism currently available (as far as I can see) to implement the PyNN Projection API in an efficient way (without duplicating connection data at the Python level).

Is there not also a performance issue? Intuitively, it seems that calling nest.GetConnections with long lists of sources and targets must be much slower than a search with only a synapse type.

> But this is probably not a sensible use case

Consider that a given neuron has many identities: it may belong to a particular column and to a particular layer; it may belong to a particular functional class (e.g. orientation preference). For a modeller to maintain conceptual control of their model and simulation, it is sometimes helpful to use different Projection objects for conceptually different types of connections between two populations or subsets thereof.

> Also, creating loads of different synapse types in NEST is generally not a good idea, if it's not necessary, because this creates a lot of memory overhead.

For a constant number of synapse types *used* (e.g. 10), how much (in qualitative terms) would it affect memory performance to increase the *maximum* number of types from 255 to, say, 1024? i.e. what is the overhead of unused/undefined types?

**Comment by mschmidt87** [comment]
@diesmann

**Comment by jschuecker** [comment]
We came up with the following solution:
We will implement the option in NEST to store a projection id as an integer in each synapse. This projection id can be optionally passed to the Connect function, so that this feature will be optional in pyNEST while in PyNN it will be set automatically. Then PyNN can identify a projection by filtering synapses for this projection id, which would be a unique label. @apdavison, do you agree with this idea?

**Comment by apdavison** [comment]
:+1: This will solve the problem for PyNN, and I think will also be useful for people creating highly-structured networks in PyNEST directly.

**Comment by apdavison** [comment]
Is there a ticket for this proposal in the NEST issue tracker we can reference?

**Comment by jougs** [comment]
The issue is documented as https://github.com/nest/nest-simulator/issues/121 already referenced above. The implementation plan will be put there soon.

**Comment by jougs** [comment]
We have implemented the solution proposed above in https://github.com/nest/nest-simulator/pull/158, which closed https://github.com/nest/nest-simulator/issues/121 on the NEST side. The next step is to make use of the new mechanism in PyNN.

**Comment by apdavison** [comment]
There is already a PR for using the labelled synapses in PyNN - see #389
