### ISSUE TITLE
Provide SpikeSourceDeadPoisson (Poisson process with dead time)

### ISSUE THREAD

**Issue by Huitzilo** [NeuralEnsemble/PyNN#387]
Poisson processes are commonly used in neuronal modeling to mimic spike trains from cortical neurons. However, the Poisson process demonstrably overestimates the variability of real neuronal spike trains ([Deger et al., 2012](http://link.springer.com/article/10.1007%2Fs10827-011-0362-8)). 

A poisson process with dead time (i.e., refractory time) has been shown to approximate the statistics of real neuronal spike trains much better than a Poisson process, while being easier to implement than a gamma process (c.f. issue #386). Therefore, it is suggested to include a SpikeSourceDeadPoisson in the standard library (suggestions for a better name are encouraged). 

Nest already provides this in the model "[ppd_sup_generator](https://github.com/nest/nest-simulator/blob/master/models/ppd_sup_generator.h)". Algorithms are described in Deger et al. (2012), with additional implementation details provided in a [Poster]http://f1000research.com/posters/1092564#) shown at Neuroinformatics 2012.
### Reference

Moritz Deger et al, “Statistical properties of superimposed stationary spike trains”, J Comput Neurosci 2012. (http://link.springer.com/article/10.1007%2Fs10827-011-0362-8)

**Comment by apdavison** [comment]
Rather than create a new model name, we should consider adding a parameter `tau_refrac` (with default zero) to `SpikeSourcePoisson`.

This has the advantage of not cluttering the model namespace, although at the cost of complexifying the implementation (e.g. the parameter could not be changed from zero after the network was built).

If we decide to add a new model, I prefer `SpikeSourcePoissonRefractory`.

**Comment by apdavison** [comment]
Added in 21e2d02
