### ISSUE TITLE
AssertionError: `size` must be an integer or a tuple of ints. You have supplied a <type 'float'>

### ISSUE THREAD

**Issue by ruthvik92** [NeuralEnsemble/PyNN#535]
It's a minor issue but I though of reporting it, I wrote `p.Population(Neurons.....)` where Neurons=11.0( I got this number from previous calculations, I can convert it to 11(int) though).
```python
 Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/pyNN/neuron/populations.py", line 81, in __init__
  structure, initial_values, label)
  File "/usr/local/lib/python2.7/dist-packages/pyNN/common/populations.py", line 619, in __init__
  assert isinstance(size, tuple), "`size` must be an integer or a tuple of ints. You have supplied a %s" % type(size)
 ```

**Comment by apdavison** [comment]
I'm not sure what the issue is. The error message explains what the user error is.

It would be better to raise a ValueError than an assertion - is this the issue?

**Comment by appukuttan-shailesh** [comment]
@ruthvik92 : PyNN intentionally does not handle conversion from float to integer, and leaves this to the user. This helps eliminate any scope for confusion. For example, if `size` (from some calculations) = 11.5, the user may expect this to be rounded-up to 12, but because of floating point representation issues ([see this for example](https://unix.stackexchange.com/questions/240112/weird-float-rounding-behavior-with-printf)) this could infact be rounded-down to 11.

So it is simpler, and probably wise, to leave this to the user.

**Comment by ruthvik92** [comment]
@apdavison I think @appukuttan-shailesh clarified my doubts. I was wondering why was PyNN not rounding off instead of throwing an assertion.
