### ISSUE TITLE
SpikeSourcePoisson not random?

### ISSUE THREAD

**Issue by andrewgait** [NeuralEnsemble/PyNN#621]
This was pointed out to me by a NEST / SpiNNaker user; they were running simple synfire chains along with a SpikeSourcePoisson using NEST and SpiNNaker, and each time they ran using NEST (which in their particular case, means they are using the default in PyNN) they get the same answer, whereas they should be getting different answers (which they do on SpiNNaker because our implementation passes in a different random seed each time when building the number sequence).  It seems to me from looking at RandomSpikeSource:

https://github.com/NeuralEnsemble/PyNN/blob/master/pyNN/neuron/cells.py#L518

that the seed will be the same each time a script that runs on the same number of MPI processors is run, as state.native_rng_baseseed appears to be set to zero each time, but I might be missing something... ?  Is there something this user should be doing in NEST instead, or is this an oversight in PyNN?

**Comment by apdavison** [comment]
This is a deliberate choice in PyNN. Running the same script twice should always give the same results unless the user has made a deliberate choice for it to behave otherwise (by explicitly changing the seed), e.g.
```
import random
setup(grng_seed=random.randint(0, 1000000))
```

Ideally, the behaviour of sPyNNaker should be changed to match, although I realise this might have an impact on existing scripts.

**Comment by apdavison** [comment]
Added more information to the documentation.
