### ISSUE TITLE
matplotlib needs capping for python 3.6

### ISSUE THREAD

**Issue by Christian-B** [NeuralEnsemble/PyNN#710]
Beginning with Matplotlib 3.4, Python 3.7 or above is required.

Found while testing we saw:
Searching for pynn<0.10.0,>=0.9.1
Reading https://pypi.org/simple/pynn/
Downloading https://files.pythonhosted.org/packages/21/64/716258bf663871b5cdec0521dc76727153bbe750fd1d804926f6ac1f8781/PyNN-0.9.6.tar.gz#sha256=d85226800e30bc1692d3f84485c3fa20b921c2ab55f1201d0a3bf23432e16cd2
Best match: PyNN 0.9.6
Processing PyNN-0.9.6.tar.gz
Writing /tmp/easy_install-9xagyksj/PyNN-0.9.6/setup.cfg
Running PyNN-0.9.6/setup.py -q bdist_egg --dist-dir /tmp/easy_install-9xagyksj/PyNN-0.9.6/egg-dist-tmp-ovlgzz2_

....

Searching for matplotlib
Reading https://pypi.org/simple/matplotlib/
Downloading https://files.pythonhosted.org/packages/9c/e6/209705cb9e41d3a6f38b2782c5fdc55e335e7205eb0eca028485a6666427/matplotlib-3.4.0rc1.tar.gz#sha256=f4ee7bb15bf01cd4c6352f8343f4d27fd8ad36bb88640eb244525fe648005d19
Best match: matplotlib 3.4.0rc1
Processing matplotlib-3.4.0rc1.tar.gz
Writing /tmp/easy_install-q1qupzv5/matplotlib-3.4.0rc1/setup.cfg
Running matplotlib-3.4.0rc1/setup.py -q bdist_egg --dist-dir /tmp/easy_install-q1qupzv5/matplotlib-3.4.0rc1/egg-dist-tmp-hr25cq7v
error: Setup script exited with 
Beginning with Matplotlib 3.4, Python 3.7 or above is required.
You are using Python 3.6.12.

==============

The suggested fix is to change setup.py to
matplotlib < 3.4; python_version == '3.6'
matplotlib; python_version >= '3.7'

We also do:
numpy > 1.13, < 1.20; python_version == '3.6'
numpy > 1.13, < 1.21; python_version == '3.7'
numpy; python_version >= '3.8'

**Comment by apdavison** [comment]
Thanks for this @Christian-B 

In the short term, this problem has gone away since we now require a minimum of Python 3.7, which is compatible with the latest releases of numpy and matplotlib according to PyPI. I've updated the setup.py in b6e818e8.

Longer term, I think the Python ecosystem really needs a better resolver; the maintainers of individual packages shouldn't have to deal with this kind of transitive constraint manually. It seems the pip developers are working on improving their resolver, so things might improve soon.
